# Generated by Django 3.0.5 on 2020-06-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('team_name', models.CharField(max_length=50)),
                ('sports', models.CharField(max_length=50)),
                ('college_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Players_Detail',
            },
        ),
    ]
